const errors = require('./errors');

const requiredType = ({ table, name }) => {
  return `The definition of the TYPE in the schema: ${table.toUpperCase()}, ${
    errors.required
  }, property name: ${name.toUpperCase()}}`;
};

const errorType = ({ key, type }) => {
  return `the key ${key.toUpperCase()} must be a ${type}`;
};

const invalidKeyType = ({ table, name }) => {
  return `Invalid keyType in the schema ${table.toUpperCase()}, property name: ${name.toUpperCase()}`;
};

const invalidAutoGenerated = ({ table, name }) => {
  return `Invalid autoGenerated in the schema ${table.toUpperCase()}, property name: ${name.toUpperCase()}`;
};

module.exports = {
  requiredType,
  errorType,
  invalidKeyType,
  invalidAutoGenerated
};
