const { schemaDefinition } = require("./build-models");
const {
  types: { dataTypes }
} = require("./config");

const FilesSchema = schemaDefinition("files", {
  id: {
    type: dataTypes.STRING,
    keyType: dataTypes.HASH,
    autoGenerated: true
  },
  filename: {
    type: dataTypes.STRING,
    required: true
  },
  active: {
    type: dataTypes.BOOLEAN
  },
  ext: {
    type: dataTypes.STRING
  },
  createdAt: {
    type: dataTypes.DATE,
    defaultValue: "2019-06-23"
  },
  updatedAt: {
    type: dataTypes.DATE,
    defaultValue: "2019-06-23"
  }
});

const test = async () => {
  try {
    const a = await FilesSchema({
      id: "699dc263-e3e4-44a4-8b16-59916aed6fe7"
    }).findByProperties();

    console.log(a);
  } catch (err) {
    console.log(err);
  }
};

test();
